### PR TITLE
Fix fips compliance 272

### LINKED ISSUE #272: crypto.createHash('md5') fails in a FIPS-enabled environment
## Description

Our team is building an `operator` based on `cdk8s` and one of our deployment targets is a [FIPS-enabled](https://en.wikipedia.org/wiki/Federal_Information_Processing_Standards) kubernetes cluster. When running `cdk8s` (and by proxy the `constructs` library), we encounter the following error when attempting to to run a `synth`:

```
Error: error:060800C8:digital envelope routines:EVP_DigestInit_ex:disabled for FIPS
```

## Root Cause

The root-cause of this bug is [this line](https://github.com/aws/constructs/blob/master/src/private/uniqueid.ts#L73) where `crypto.createHash('md5')` is invoked. According to [the internet](https://github.com/s3tools/s3cmd/issues/1005#issuecomment-424765923) the `md5` crypto hash algorithm is considered insecure by FIPS standards and is thus disabled in the underlying `openssl` libraries when the operating system is running in FIPS mode.

## Repro

(In a FIPS-enabled cluster. Not sure how to easily reproduce this)

```js
const crypto = require('crypto');
crypto.createHash('md5').update(path.join('/')).digest("hex");
```

## Proposed Solution

I believe that the point of the offending line is simply to compute a unique value for the given string `path`, so I think we can simply replace `'md5'` with a FIPS-approved algorithm like `sha1` or `sha256`. I've tested both and they both produce valid hash values.

## Volunteering!

I'd be happy to try to fix this one and submit a PR

### PR DESCRIPTION
**Pull request by gabe-l-hart**
*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

This fixes #272 

I have verified that when used in a FIPS enabled cluster, we no longer see the reported issue.

### CODE REVIEW

**Review by eladb — COMMENTED** [review]
LGTM, @iliapolo what do you think?

**Review by eladb — CHANGES_REQUESTED** [review]
I take my "LGTM" back... we won't be able to change how uniqueId calculates hashes because it will break all CDK code that uses this property to create stable names.

As part of #250, I think we need to basically soft-deprecate `uniqueId` in favor of something more ubiquitous and then we can use a different hash algorithm.

**Comment by gabe-l-hart** [comment]
@eladb Interesting, I was afraid that might be the case. Ultimately, I think this is an issue where what we want is the `md5` hash algorithm but we want it for a non-crypto usecase so it _should_ be acceptable for FIPS. I'll look a bit more to see if there is another non-crypto md5 implementation that we could be using instead.

**Comment by gabe-l-hart** [comment]
So, a couple of options come to mind for me:

1. We could use a pure-js implementation of `md5` like [this one](https://www.npmjs.com/package/md5). That would keep the hashes consistent, but it would add a dependency to `constructs` which currently has none

1. We could add an env-var check in `uniqueId` and use `sha1` if it indicated FIPS-enablement

Thoughts?

**Comment by eladb** [comment]
@rix0rrr @RomainMuller @njlynch Interested on your take here

**Comment by gabe-l-hart** [comment]
I noted it in the issue, but we've got [a workaround script](https://github.com/aws/constructs/issues/272#issuecomment-705025353) to unblock our team on this, so feel free to discuss as needed. Whatever fix feels right to the team should be fine with us once it's ready, and I'll be happy to verify it in our FIPS environment.

**Comment by eladb** [comment]
Superseded by https://github.com/aws/constructs/pull/314

**Pull request closed without merging**
